### ISSUE TITLE
[Bug 🐞]: Directory for the model and texture files is incorrect in all 4 .cfg files

### ISSUE THREAD

**Issue by help137** [zer0Kerbal/DropTanks#46]
### Brief description of your issue (aka the problem)

The directory for the model and textures doesn't match the folder structure in the archive in all 4 .cfg files. 

As an example, In the file is: "model = KerbalHacks/**WrapperTank**/WrapperTank"

It should be: "model = KerbalHacks/**DropTankWrapper**/WrapperTank"

-K

### Operating system

Windows 10-64

### KSP version

1.12.4

### Version of addon

1.0.0.0

### Steps to reproduce the behavior or issue

Install

### Expected behavior

Parts in VAB

### Actual behavior

No parts in VAB

### Environment

```shell
Mod: 1.0.0.0
KSP: 1.12.4
Source: Curseforge
OS: Windows 10-64
```

### How did you download and install this?

CurseForge (download and manual installation)

**Comment by zer0Kerbal** [comment]
Thank you @help137 

Found the issue - _if I remember correctly_ I was waiting for CurseForge to approve the agency listing, and just got sidetracked and didn't publish the actual update (just the archival) on CurseForge/SpaceDock. 

Corrected. 

links have been updated [Download here](https://www.curseforge.com/kerbal/ksp-mods/droptanks/files/4296178)
