### ISSUE TITLE
[Bug 🐞]: Tweakscale patch only affects long tank.

### ISSUE THREAD

**Issue by help137** [zer0Kerbal/DropTanks#52]
### Brief description of your issue (aka the problem)

The included Tweakscale patch( DropTankWrapper/Compatability/TweakScale.cfg) only affects the "wrapper" tank. 

To correct, change line 8 to:

`@PART[drop-tank-*-125]:NEEDS[KerbalHacks/DropTankWrapper,TweakScale]:FOR[DropTankWrapper]`

### Operating system

n/a

### KSP version

1.12.5

### Version of addon

1.0.99.0

### Steps to reproduce the behavior or issue

add part, right click and attempt to adjust scale

### Expected behavior

Tweakscale slider to be present on all parts

### Actual behavior

Tweakscale slider missing on all but "wrapper" tank

### Environment

```shell
Mod: 1.0.99.0
KSP: 1.12.5
Download: Curseforge/Manual
```

### How did you download and install this?

CurseForge (download and manual installation)

**Comment by zer0Kerbal** [comment]
https://github.com/zer0Kerbal/DropTanks/blob/b7381b0f69e779fdb2ff431862f581d338a387da/GameData/KerbalHacks/DropTanks/Compatibility/TweakScale.cfg#L8

**Comment by zer0Kerbal** [comment]
@help137 Thank you!
