### ISSUE TITLE
[Request]: B9 Fuel Switch Patch

### ISSUE THREAD

**Issue by help137** [zer0Kerbal/DropTanks#58]
### Description of the new feature / enhancement

A B9 Fuel Switch patch to allow the drop tanks to be different types would be very helpful. 
### Proposed technical implementation details

I have the Patch written up and tested, along with Localization updates. Just trying to figure out how to get it to you.

**Comment by help137** [comment]
[B9fuelswitch-DropTank.zip](https://github.com/zer0Kerbal/DropTanks/files/10481077/B9fuelswitch-DropTank.zip)

**Comment by zer0Kerbal** [comment]
Thank you @help137 

best way is the fork/commit/PR method; however if you are unsure on how that works - then just drag'n'drop or copy'n'paste into this issue thread.

**Comment by help137** [comment]
I think I figured out the Fork/commit/PR method. Should be out there for your review if I did it right.

**Comment by zer0Kerbal** [comment]
> I think I figured out the Fork/commit/PR method. Should be out there for your review if I did it right.

@help137 yes you did. I will review in the next couple of days - am also waiting for the results of a [reddit poll]()https://www.reddit.com/r/KerbalSpaceProgram/comments/10ix089/which_size_drop_tank_do_you_want_to_see_next/ to decide which size to add next. ⏭️
